### ISSUE TITLE
Firefox tests hanging

### ISSUE THREAD

**Issue by igorsantos07** [edmondscommerce/selenium-server#2]
The extension works just fine when running Chrome tests. However, Firefox tests make the browser open and it does not do anything. The tests hang after a timeout.

Using `se/selenium-server-standalone` for Firefox tests works just fine. They have Selenium 2.46.

I have Firefox 38.0.

**Comment by edmondscommerce** [comment]
Please try putting 2.46 into the binaries folder and see if that resolves

If so please feel free to update the MAJOR_VERSION in the run script and do a pull request
